name: CCX Admin Guide - Update Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - wiki/**

jobs:
  call-build-flow:
    uses: ./.github/workflows/update_customer_workflow.yml
    with:
      CUST: "ccxadmin"
      wikiRepo: "ccx-admin-guide"
    secrets:
      deployKey: ${{ secrets.DEPLOY_KEY_CCXADMIN }}
