name: Glesys - Update Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - wiki/**

jobs:
  call-build-flow:
    uses: ./.github/workflows/update_customer_workflow.yml
    with:
      CUST: "glesys"
      wikiRepo: "ccx-glesys"
    secrets:
      deployKey: ${{ secrets.DEPLOY_KEY_GLESYS }}
